add support for the '-t' operator

diff --git a/tests/conditionals/[...].yml b/tests/conditionals/[...].yml
--- a/tests/conditionals/[...].yml
+++ b/tests/conditionals/[...].yml
@@ -560,3 +560,27 @@ cases:
         1: 0
         2: 1
         3: 1
+
+  - name: "can test that a file is a terminal using the [...] syntax"
+    # by the way, we wrap the call within a group {...} because we don't want tests to fail if redirections on [...] is buggy.
+    script: |
+      {
+        [ -t 3 ]
+      } 3>/dev/null
+
+      echo '1': $?
+
+      {
+        [ -t 3 ]
+      } 3>/dev/ptmx
+
+      echo '2': $?
+
+      [ -t invalid-fd ]
+      echo '3': $?
+
+    expect:
+      stdout: |
+        1: 1
+        2: 0
+        3: 1
